from gymnasium.envs.registration import register

register(id='MTXEnvBase', entry_point='envs:MTXEnvBase')
register(id='MTXEnvSyn', entry_point='envs:MTXEnvSyn')
register(id='MTXEnvLongSimple', entry_point='envs:MTXEnvLongSimple')
register(id='MTXEnvLongFull', entry_point='envs:MTXEnvLongFull')
register(id='MTXEnvShortSimple', entry_point='envs:MTXEnvShortSimple')
register(id='MTXEnvShortFull', entry_point='envs:MTXEnvShortFull')
register(id='MTXEnvLongTest', entry_point='envs:MTXEnvLongTest')
register(id='MTXEnvShortTest', entry_point='envs:MTXEnvShortTest')
register(id='MTXEnvTrader', entry_point='envs:MTXEnvTrader')
register(id='MTXEnvRealTimeTrader', entry_point='envs:MTXEnvRealTimeTrader')
register(id='MTXEnvTraderLeverage', entry_point='envs:MTXEnvTraderLeverage')
register(id='MTXEnvLongLeverage', entry_point='envs:MTXEnvLongLeverage')
register(id='MTXEnvShortLeverage', entry_point='envs:MTXEnvShortLeverage')
register(id='LongSimpleMicro', entry_point='envs:LongSimpleMicro')
register(id='LongFullMicro', entry_point='envs:LongFullMicro')
register(id='ShortSimpleMicro', entry_point='envs:ShortSimpleMicro')
register(id='ShortFullMicro', entry_point='envs:ShortFullMicro')
register(id='AbstractObsTrader', entry_point='envs:AbstractObsTrader')
register(id='MTXEnvTraderOneShare', entry_point='envs:MTXEnvTraderOneShare')
register(id='LongSimpleV2', entry_point='envs:LongSimpleV2')
register(id='LongFullV2', entry_point='envs:LongFullV2')
register(id='ShortSimpleV2', entry_point='envs:ShortSimpleV2')
register(id='ShortFullV2', entry_point='envs:ShortFullV2')
register(id='MTXEnvSimple', entry_point='envs:MTXEnvSimple')
register(id='MTXEnvFull', entry_point='envs:MTXEnvFull')
register(id='MTXEnvTraderV2', entry_point='envs:MTXEnvTraderV2')